# Generated by Django 6.0.5 on 2026-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(default='Emirates', max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('no', models.IntegerField()),
                ('From', models.TextField(max_length=20)),
                ('To', models.TextField(max_length=20)),
                ('Departure', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Price', models.IntegerField()),
                ('your_name', models.TextField(default='Emirates', max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Phone_no', models.IntegerField()),
                ('Adhaar_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('seat_class', models.TextField(default='Emirates', max_length=20)),
                ('seat_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(default='Emirates', max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('no', models.IntegerField()),
                ('From', models.TextField(max_length=20)),
                ('To', models.TextField(max_length=20)),
                ('Departure', models.TimeField(max_length=20)),
                ('Date', models.DateField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
