# Generated by Django 6.0.5 on 2026-05-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='Phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
